import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { AlertProvider } from "./components/alert/alert_context";
import { ConfirmProvider } from "./components/alert/confirm_context";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Smith Origin Official Website",
  description: "Generated by create next app", icons: [{ rel: "icon", url: "/Logo.png" }]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className} scroll-smooth`}>
      <body>
        <AlertProvider>
          <ConfirmProvider>
            {children}
          </ConfirmProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
