import type { Metadata } from "next";
import { Sora } from "next/font/google";
import Header from "./components/navbar";
import "./globals.css";

const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.className} antialiased`}>
        <Header />
        <main className="container mx-auto px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
